I'm sorry, but an uncaught exception occurred.

While loading the script.
ScriptError: Name ('renpy/common/000atl.rpy', 1649732250, 55) is defined twice, at renpy/common/000atl.rpy:25 and game/Contents/Resources/autorun/renpy/common/000atl.rpyc:25.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Applications/renpy-8.1.1-sdk/renpy/bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "/Applications/renpy-8.1.1-sdk/renpy/main.py", line 492, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "/Applications/renpy-8.1.1-sdk/renpy/script.py", line 310, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "/Applications/renpy-8.1.1-sdk/renpy/script.py", line 888, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn) # type: ignore
  File "/Applications/renpy-8.1.1-sdk/renpy/script.py", line 525, in finish_load
    check_name(node)
  File "/Applications/renpy-8.1.1-sdk/renpy/script.py", line 501, in check_name
    raise ScriptError("Name %s is defined twice, at %s:%d and %s:%d." %
ScriptError: Name ('renpy/common/000atl.rpy', 1649732250, 55) is defined twice, at renpy/common/000atl.rpy:25 and game/Contents/Resources/autorun/renpy/common/000atl.rpyc:25.

macOS-14.2.1-arm64-arm-64bit arm64
Ren'Py 8.1.1.23060707
RachaBardDemo 1.0
Tue Jan 30 10:09:02 2024
