I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 25, in script call
    call stb3_page1
  File "game/stb3_page1.rpy", line 21, in script call
    call stb3_page2
  File "game/stb3_page2.rpy", line 5, in script call
    call stb3_page3
  File "game/script.rpy", line 25, in script call
    call stb3_page1
  File "game/stb3_page1.rpy", line 21, in script call
    call stb3_page2
  File "game/stb3_page2.rpy", line 5, in script call
    call stb3_page3
ScriptError: could not find label 'stb3_page3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 25, in script call
    call stb3_page1
  File "game/stb3_page1.rpy", line 21, in script call
    call stb3_page2
  File "game/stb3_page2.rpy", line 5, in script call
    call stb3_page3
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 25, in script call
    call stb3_page1
  File "game/stb3_page1.rpy", line 21, in script call
    call stb3_page2
  File "game/stb3_page2.rpy", line 5, in script call
    call stb3_page3
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'stb3_page3'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
RachaBardDemo 1.0
Wed Sep 13 10:19:53 2023
